
services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - my_network

  web:
    build: 
      context: ./project
      dockerfile: Dockerfile
    container_name: dockerappweb
    entrypoint: ["/app/entrypoint.sh"] 
    volumes:
      - ./project:/app
    ports:
      - "7000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
